"""Conversor de dialecto PLY: Brush → opensplat-inria (M1, puente de eval).

Brush v0.3.0 escribe las 59 propiedades en orden ALFABÉTICO (f_rest_0,1,10,11…
léxico; x,y,z al final) y sin normales; loadPly del renderer parcheado espera
el layout inria (x,y,z,nx,ny,nz,f_dc×3,f_rest_0-44 numérico,opacity,scale×3,
rot×4) + el comment "at iteration N". El mapeo es POR NOMBRE — el orden léxico
se disuelve solo — y nx/ny/nz se rellenan a 0 (no se usan). Los ejes NO se
tocan: las gaussianas viven en el mismo frame mundo que las cámaras COLMAP que
Brush consumió; el gate de OJO contra el incumbente valida la geometría (regla:
no transformar a ciegas lo que se puede verificar mirando).

Uso: python3 ply_bridge.py brush.ply out.ply [iteration]
"""
import sys

import numpy as np


TARGET = (["x", "y", "z", "nx", "ny", "nz", "f_dc_0", "f_dc_1", "f_dc_2"]
          + [f"f_rest_{i}" for i in range(45)]
          + ["opacity", "scale_0", "scale_1", "scale_2", "rot_0", "rot_1", "rot_2", "rot_3"])


def convert(src: str, dst: str, iteration: int = 2000) -> int:
    data = open(src, "rb").read()
    he = data.index(b"end_header\n") + len(b"end_header\n")
    header = data[:he].decode()
    props = [l.split()[-1] for l in header.splitlines() if l.startswith("property")]
    n = int(next(l for l in header.splitlines() if l.startswith("element vertex")).split()[-1])
    if not all(l.split()[1] == "float" for l in header.splitlines() if l.startswith("property")):
        raise SystemExit("propiedad no-float — dialecto inesperado, no convertir a ciegas")
    arr = np.frombuffer(data[he:he + n * len(props) * 4], dtype="<f4").reshape(n, len(props))
    cols = {p: i for i, p in enumerate(props)}
    out = np.zeros((n, len(TARGET)), dtype="<f4")
    missing = []
    for j, name in enumerate(TARGET):
        if name in cols:
            out[:, j] = arr[:, cols[name]]
        elif name not in ("nx", "ny", "nz"):
            missing.append(name)
    # INTERLEAVING f_rest: Brush escribe coeff-major (c0:RGB,c1:RGB,…); inria espera
    # channel-major (R0-14,G0-14,B0-14). Adjudicado por render 11-jul: sin permutar
    # el SH EMPEORA el error (22.5 vs 21.1 con f_rest=0); permutado lo elimina
    # (21.1). A 2000 steps SH aporta ~0 (subentrenado) — adjudicación FINAL del
    # signo positivo en celda 3 (30000 steps, SH real).
    fr0 = TARGET.index("f_rest_0")
    block = out[:, fr0:fr0 + 45]
    out[:, fr0:fr0 + 45] = block.reshape(n, 15, 3).transpose(0, 2, 1).reshape(n, 45)
    if missing:
        raise SystemExit(f"faltan propiedades no-opcionales: {missing}")
    hdr = ("ply\nformat binary_little_endian 1.0\n"
           f"comment Generated by opensplat at iteration {iteration}\n"
           f"element vertex {n}\n"
           + "".join(f"property float {p}\n" for p in TARGET)
           + "end_header\n")
    with open(dst, "wb") as f:
        f.write(hdr.encode())
        f.write(out.tobytes())
    return n


if __name__ == "__main__":
    n = convert(sys.argv[1], sys.argv[2], int(sys.argv[3]) if len(sys.argv) > 3 else 2000)
    print(f"convertidas {n:,} gaussianas → {sys.argv[2]}")
